clc;
clear all;
Fs = 12000;
fm = 400;
fc = 3000;
dt = 0.2;
t = 0:1/Fs:0.02;
Am = 1.5;
m1 = 0.4;
m2 = 1;
m3 = 1.8;
Ac1 = Am/m1;
Ac2 = Am/m2;
Ac3 = Am/m3;
mt = Am*sin(2*pi*fm*t);
ct1 = Ac1*cos(2*pi*fc*t);
ct2 = Ac2*cos(2*pi*fc*t);
ct3 = Ac3*cos(2*pi*fc*t);
st1 = Ac1.*(1+m1*sin(2*pi*fm*t)).*cos(2*pi*fc*t);
st2 = Ac2.*(1+m2*sin(2*pi*fm*t)).*cos(2*pi*fc*t);
st3 = Ac3.*(1+m2*sin(2*pi*fm*t)).*cos(2*pi*fc*t);

figure();
subplot(411),plot(t,mt);
title("m(t)");
xlabel("amplitude");
ylabel("time");
subplot(412),plot(t,st1);
title("s(t)");
ylabel("amplitude");
xlabel("time");
subplot(413),plot(t,st2);
title("s(t)");
ylabel("amplitude");
xlabel("time");
subplot(414),plot(t,st3);
title("s(t)");
ylabel("amplitude");
xlabel("time");

N = 1024;
m = 1;
f = linspace(-Fs/2,Fs/2,N);
mtf = fft(mt,N);
mtf1 = fftshift(abs(mtf)/N);
ctf = fft(ct2,N);
ctf1 = fftshift(abs(ctf)/N);
stf = fft(st2,N);
stf1 = fftshift(abs(stf)/N);
figure();
subplot(311), plot(f,mtf1);
title("magnitude response of m(t)");
ylabel("amplitude");
xlabel("frequency");
subplot(312), plot(f,ctf1);
title("magnitude response of c(t)");
ylabel("amplitude");
xlabel("frequency");
subplot(313), plot(f,stf1);
title("magnitude response of s(t) ");
ylabel("amplitude");
xlabel("frequency");

flow = fc;
[bl, al] = butter(5, flow / (Fs / 2), 'low');
[Hlp, Flp]=freqz(bl, al,Fs/2);
st2 = st2.*st2;
st2 = 2*st2;
xt = st2;
yt = filter (bl,al,xt);
rt = sqrt(yt);
Dc = mean(rt);
mt3 = rt - Dc;
figure();
subplot(311), plot(t,xt);
title("x(t)");
ylabel("amplitude");
xlabel("time");
subplot(312), plot(t,yt);
title("y(t)");
ylabel("amplitude");
xlabel("time");
subplot(313), plot(t,rt);
title("r(t)");
ylabel("amplitude");
xlabel("time");
figure();
plot(t,mt);
title("m(t)");
ylabel("amplitude");
xlabel("time");
hold on;
plot(t,mt3);
title("m'(t)");
ylabel("amplitude");
xlabel("time");

