clc;
clear all;
close all;

Fs = 4000;
fm = 40;
fc = 150;
t = 0 : 1/Fs : 0.5;
Am = 3;
Ac = 1;
mt = 3*cos(2*pi*fm*t);
ct = cos(2*pi*fc*t);
kf1 = 6;
kf2 = 12;
kf3 = 18;
ut1 = cos((2*pi*fc*t) + (2*pi*kf1*cumsum(mt,2)*(1/Fs)));
ut2 = cos((2*pi*fc*t) + (2*pi*kf2*cumsum(mt,2)*(1/Fs)));
ut3 = cos((2*pi*fc*t) + (2*pi*kf3*cumsum(mt,2)*(1/Fs)));

figure(1);
subplot(411), plot(t,mt);
title('m(t)');
ylabel('Amplitude');
xlabel('Time (s)');
subplot(412), plot(t,ut1);
title('Modulated Signal-1 s1(t)');
ylabel('Amplitude');
xlabel('Time (s)');
subplot(413), plot(t,ut2);
title('Modulated Signal-2 s2(t)');
ylabel('Amplitude');
xlabel('Time (s)');
subplot(414), plot(t,ut3);
title('Modulated Signal-3 s3(t)');
ylabel('Amplitude');
xlabel('Time (s)');
N = length(t);
f = linspace(-Fs/2,Fs/2,N);
mtf = abs(fftshift(fft(mt, N)))/N;
ut1f = abs(fftshift(fft(ut1, N)))/N;
ut2f = abs(fftshift(fft(ut2, N)))/N;
ut3f = abs(fftshift(fft(ut2, N)))/N;
figure(2);
subplot(411), plot(f,mtf);
title('M(f)');
ylabel('Amplitude');
xlabel('Frequency');
subplot(412), plot(f,ut1f);
title('S1(f)');
ylabel('Amplitude');
xlabel('Frequency');
subplot(413), plot(f,ut2f);
title('S2(f)');
ylabel('Amplitude');
xlabel('Frequency');
subplot(414), plot(f,ut3f);
title('S3(f)');
ylabel('Amplitude');
xlabel('Frequency');
demod1 = Am*fmdemod(ut1,fc,Fs,Am*kf1);
demod2 = Am*fmdemod(ut2,fc,Fs,Am*kf2);
demod3 = Am*fmdemod(ut3,fc,Fs,Am*kf3);

figure(3);
subplot(311), plot(t,demod1);
title('Demodulation of s1(t)');
ylabel('Amplitude');
xlabel('Time(s)');
hold on;
plot(t,mt);
subplot(312), plot(t,demod2);
title('Demodulation of s2(t)');
ylabel('Amplitude');
xlabel('Time(s)');
hold on;
plot(t,mt);
subplot(313), plot(t,demod3);
title('Demodulation of s3(t)');
ylabel('Amplitude');
xlabel('Time(s)');
hold on;
plot(t,mt);

